version: '3'
services:
  registry:
    image: scg-demo-registry:latest
    container_name: registry
    expose: 
      - "8761"
  greeting-service:
    image: scg-demo-service:latest
    container_name: greeting-service
    expose: 
      - "8762"
    depends_on: 
      - "registry"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry:8761/eureka
  gateway:
    image: scg-demo-gateway:latest
    container_name: gateway
    ports:
      - "127.0.0.1:8080:8760"
    depends_on: 
      - registry
      - greeting-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry:8761/eureka
